#include<iostream>
#include<string>
using namespace std;

class Box
{
private:
    double length;
    double breadth;
    double height; 
public:
    Box(double side);
    Box(double len,double bre,double hei);
    double surface_area();
    double volume();
};
Box::Box(double side)
{
    length = breadth = height = side;
}
Box::Box(double len,double bre, double hei)
{
    length = len;
    breadth = bre;
    height = hei;
}
double Box::surface_area()
{
    return 2*(length*breadth + length*height + breadth * height);
}
double Box:: volume()
{
    return length*breadth*height;
}

int main()
{
    // without pointers 
    Box mybox = Box(10);
    cout << "First Box"<<endl;
    cout <<"area_surface "<< mybox.surface_area() << endl;
    cout << "Volume " << mybox.volume() << endl;
    Box mybox1 = Box(12,12,23);
    cout << "Second Box"<<endl;
    cout <<"area_surface "<< mybox1.surface_area() << endl;
    cout << "Volume " << mybox1.volume() << endl;
    // with pointers 
    Box *mybox2 = new Box(5);
    cout <<"Third Box " << endl;
    cout << "area_surface " << mybox2->surface_area()<< endl;
    cout << "volume " << mybox2->volume() << endl;

    Box *mybox3 = new Box(1,2,3);
    cout << "Fourth Box "<<endl;
    cout << "area_surface " << mybox3->surface_area() << endl;
    cout << "Volume " << mybox3->volume() << endl;

}

/*
    If you don't provide any constructor then the constructor is generated by c++ which is non parametric in nature 
    But if provide some constructor by yourself then you have to accept that c++ will now not generate any no argument constructor 
     

*/


